### ISSUE TITLE
Fix Database is Locked errrors

### ISSUE THREAD

**Issue by person594** [person594/fotaro#7]
presumably require the DB lock when reading from the database as well

**Comment by person594** [comment]
Example:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fotaro/fotaro/src/fotaro/cas.py", line 289, in daemon
    self.update()
  File "/home/fotaro/fotaro/src/fotaro/cas.py", line 311, in update
    self._add_file(fs_path)
  File "/home/fotaro/fotaro/src/fotaro/cas.py", line 260, in _add_file
    c.execute("REPLACE INTO Files VALUES(?, ?, ?, ?)", (path, hsh, modified, mime))
  File "/home/fotaro/fotaro/src/fotaro/fotaro.py", line 34, in __exit__
    self.mcon._con.commit()
sqlite3.OperationalError: database is locked
```
